spring.application.name=subscription-billing-platform


jwt.secret=mysupersecretkeyatleast32characterslong
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000 


spring.datasource.url=jdbc:postgresql://localhost:5433/subscription_billing
spring.datasource.username=postgres
spring.datasource.password=Test@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true